#!/usr/bin/env node
// Headless benchmark suite — the "100+ nodes" claim with numbers attached.
//
//   node bench/run.js
//
// Simulates fixed missions at growing fleet sizes through the SAME code the
// browser runs (loaded headlessly via the shared vm harness), measures
// wall-clock cost per simulated second, and writes bench/BASELINE.md so a
// PR that regresses scale performance shows up in review as a diff.

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { loadCore } = require('../test/helpers/sim.js');

const R = require('../js/radios.js');
const A = require('../js/airframes.js');

const SIM_SECONDS = 90;
const FLEET_SIZES = [10, 50, 100, 140];

function runOnce(n) {
  const ctx = loadCore();
  const s = ctx.makeSwarm({
    count: n,
    airframe: A.AIRFRAMES.find(a => a.id === 'q450'),
    radio: R.RADIOS.find(r => r.id === 'rfd900x'),
    envFactor: 1,
    targetX: 2400, targetY: -600,
    altitudeM: 70,
    seed: 900 + n,
    videoOn: true,
    videoKbps: 250, // payload traffic stresses the network layer honestly
  });
  let st = null;
  const t0 = process.hrtime.bigint();
  while (s.time < SIM_SECONDS) st = ctx.stepSwarm(s, 0.25);
  const wallMs = Number(process.hrtime.bigint() - t0) / 1e6;
  return {
    n,
    wallMs,
    msPerTick: wallMs / (SIM_SECONDS / 0.25),
    speedup: SIM_SECONDS / (wallMs / 1000),
    delivered: s.net.delivered,
    droppedPct: 100 * s.net.dropped / Math.max(1, s.net.delivered + s.net.dropped),
    uptimePct: 100 * s.stats.connSec / s.stats.tSec,
  };
}

function fmtRow(r) {
  return '| ' + r.n + ' | ' + r.msPerTick.toFixed(2) + ' | ' +
    r.speedup.toFixed(1) + '× | ' + r.delivered.toLocaleString() +
    ' | ' + r.uptimePct.toFixed(0) + '% | ' + r.droppedPct.toFixed(1) + '% |';
}

function main() {
  console.log('Benchmarking fleet sizes ' + FLEET_SIZES.join(', ') + ' for ' +
    SIM_SECONDS + ' sim-seconds each…');
  const rows = [];
  for (const n of FLEET_SIZES) {
    process.stdout.write('  n=' + n + ' … ');
    const r = runOnce(n);
    rows.push(r);
    console.log(r.msPerTick.toFixed(2) + ' ms/tick (' + r.speedup.toFixed(1) + '× realtime)');
  }

  const md = [
    '# Scale benchmark — baseline',
    '',
    '_Generated by `node bench/run.js`. Regenerate and commit the diff whenever the_',
    '_core loop changes; a jump here is a performance regression someone should explain._',
    '',
    '- Node ' + process.version + ' · ' + os.platform() + ' ' + os.arch() +
      ' · ' + os.cpus()[0].model.trim(),
    '- Mission: RFD900x mesh @ 250 kbps video backhaul, 2.4 km objective, 90 sim-seconds, dt 0.25',
    '- The binding constraint at scale is the SHARED CHANNEL (broadcast row grows with N), not the physics.',
    '',
    '| Fleet | ms/tick | × realtime | packets | link uptime | drop |',
    '|---|---|---|---|---|---|',
    ...rows.map(fmtRow),
    '',
  ].join('\n');

  const out = path.join(__dirname, 'BASELINE.md');
  fs.writeFileSync(out, md);
  console.log('\nWrote ' + out);
}

main();
